package xenosoft.imldintelligence.module.identity.internal.model;

import lombok.Data;

import java.time.OffsetDateTime;

@Data
public class ConsentRecord {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private Long tocUserId;
    private String consentType;
    private String consentVersion;
    private Boolean signedOffline;
    private OffsetDateTime signedAt;
    private Long fileId;
    private String status;
    private String remark;
    private OffsetDateTime createdAt;
}

/**
 * CREATE TABLE consent_record (
                                id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                                patient_id              BIGINT REFERENCES patient(id),
                                toc_user_id             BIGINT REFERENCES toc_user(id),
                                consent_type            VARCHAR(32) NOT NULL,             -- CLINICAL / TOC / GENETIC / DATA_TRANSFER
                                consent_version         VARCHAR(32) NOT NULL,
                                signed_offline          BOOLEAN NOT NULL DEFAULT TRUE,    -- 线下签署
                                signed_at               TIMESTAMPTZ,
                                file_id                 BIGINT,                           -- 关联签署扫描件
                                status                  VARCHAR(32) NOT NULL DEFAULT 'VALID',
                                remark                  TEXT,
                                created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
 */