package xenosoft.imldintelligence.module.identity.internal.model;

import lombok.Data;

import java.time.OffsetDateTime;

@Data
public class Encounter {
    private Long id;
    private Long tenantId;
    private Long patientId;
    private String encounterNo;
    private String encounterType;
    private String deptName;
    private Long attendingDoctorId;
    private OffsetDateTime startAt;
    private OffsetDateTime endAt;
    private String sourceSystem;
    private OffsetDateTime createdAt;
}
/**
 * CREATE TABLE encounter (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id               BIGINT NOT NULL REFERENCES tenant(id),
                           patient_id              BIGINT NOT NULL REFERENCES patient(id),
                           encounter_no            VARCHAR(64) NOT NULL,
                           encounter_type          VARCHAR(32) NOT NULL,             -- OUTPATIENT/INPATIENT/EMERGENCY
                           dept_name               VARCHAR(100),
                           attending_doctor_id     BIGINT REFERENCES user_account(id),
                           start_at                TIMESTAMPTZ NOT NULL,
                           end_at                  TIMESTAMPTZ,
                           source_system           VARCHAR(64),                      -- HIS/EMR
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
                           UNIQUE (tenant_id, encounter_no)
);
 */